server:
  port: 8091
#  port: 6666
#  port: 8088
spring:
  datasource:
    username: root
    password: tasteSuDBA6868.
    url: jdbc:mysql://47.75.159.83:3306/taste?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      max-lifetime: 1800000
      pool-name: HikariCP
      connection-timeout: 30000
      connection-test-query: SELECT 1

  redis:
    host: 47.56.1.232
    port: 6379
    password: tasteredis666888.
    lettuce:
      pool:
        max-active: 8
        min-idle: 3
        max-idle: 8
        max-wait: -1s

taste-file-path:
  reward-code: /root/rsa/qrcode
  reward-code-zip: /root/rsa/qrcodeZip
  rsa-private-key: /root/rsa/pkcs8_private_key.pem
  wallet-eth-folder: /root/wallet

trade-match:
  ip: 127.0.0.1
  port: 9999