server:
  port: 8099
#  port: 6666
#  port: 8088
spring:
  datasource:
    username: root
    password: 88888888
    url: jdbc:mysql://localhost:3306/trade_system?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      minimum-idle: 1
      idle-timeout: 180000
      maximum-pool-size: 10
      max-lifetime: 1800000
      pool-name: HikariCP
      connection-timeout: 180000
      connection-test-query: SELECT 1
      validation-timeout: 180000

  redis:
    host: 47.106.158.56
    port: 6379
    password: luji666888
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1s
    database: 3

taste-file-path:
  reward-code: F:\qrcode
  reward-code-zip: F:\qrcodeZip
  rsa-private-key: F:\keystore\pkcs8_private_key.pem
  wallet-eth-folder: F:\wallet

trade-match:
  ip: 127.0.0.1
  port: 9999

