server:
  port: 8090
spring:
  datasource:
    username: root
    password: 88888888
    url: jdbc:mysql://localhost:3306/trade_system?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      minimum-idle: 1
      idle-timeout: 180000
      maximum-pool-size: 10
      max-lifetime: 1800000
      pool-name: HikariCP
      connection-timeout: 180000
      connection-test-query: SELECT 1
      validation-timeout: 180000

  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/trade_match
